Webkul\UVDesk\AutomationBundle\Entity\WorkflowEvents:
    type: entity
    table: null
    repositoryClass: Webkul\UVDesk\AutomationBundle\Repository\WorkflowEventsRepository
    manyToOne:
        workflow:
            targetEntity: Webkul\UVDesk\AutomationBundle\Entity\Workflow
            inversedBy: workflowEvents
            joinColumn:
                name: workflow_id
                referencedColumnName: id
                onDelete: cascade
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        eventId:
            type: integer
        event:
            type: string
            length: 191
    lifecycleCallbacks: {  }
