<?php

namespace Webkul\UVDesk\AutomationBundle\Repository;

use Doctrine\Common\Collections\Criteria;
/**
 * WorkflowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkflowRepository extends \Doctrine\ORM\EntityRepository
{
    public $safeFields = array('page','limit','sort','order','direction');
    const LIMIT = 10;

	public function getWorkflows(\Symfony\Component\HttpFoundation\ParameterBag $obj = null, $container) {
        // $userService = $container->get('user.service');
        // $currentPlan = $userService->getCurrentPlan();
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('w.id, w.name, w.status')->from($this->getEntityName(), 'w')
            ->orderBy('w.sortOrder', Criteria::ASC);
        
        // if($currentPlan && $currentPlan->getWorkflow() == 'predefind') {
        //     $qb->andWhere('w.isPredefind = 1');
        // }
        
        return ['workflows' => $qb->getQuery()->getArrayResult()];
    }
}
