<?php

namespace Webkul\UVDesk\AutomationBundle\Fixtures;

use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Bundle\FixturesBundle\Fixture as DoctrineFixture;
use Webkul\UVDesk\AutomationBundle\Entity as AutomationEntities;

class AutomationWorkflowFixtures extends DoctrineFixture
{
    private static $seeds = [
        [
            'name' => 'Ticket reply by agent',
            'description' => 'Ticket Reply added by agent',
            'conditions' => 'N;',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:29:"uvdesk.customer.mail_customer";s:5:"value";s:5:"ARTCT";}}',
            'emailTemplate' => 'ARTCT',
            'status' => '1',
            'sort_order' => '8',
            'events' => ['uvdesk.ticket.agent_reply']
        ],
        [
            'name' => 'Ticket reply by customer',
            'description' => 'Ticket reply by customer ',
            'conditions' => 'N;',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:23:"uvdesk.agent.mail_agent";s:5:"value";a:2:{s:3:"for";a:1:{i:0;s:13:"assignedAgent";}s:5:"value";s:3:"CRT";}}}',
            'emailTemplate' => 'CRT',
            'status' => '1',
            'sort_order' => '9',
            'events' => ['uvdesk.ticket.customer_reply']
        ],
        [
            'name' => 'Account validation of customer ',
            'description' => 'Account validation of customer ',
            'conditions' => 'N;',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:29:"uvdesk.customer.mail_customer";s:5:"value";s:2:"AA";}}',
            'emailTemplate' => 'AA',
            'status' => '1',
            'sort_order' => '14',
            'events' => ['uvdesk.customer.created']
        ],
        [
            'name' => 'Account activation of agent',
            'description' => 'Account activation of agent',
            'conditions' => 'N;',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:23:"uvdesk.agent.mail_agent";s:5:"value";a:2:{s:3:"for";a:1:{i:0;s:9:"baseAgent";}s:5:"value";s:2:"AA";}}}',
            'emailTemplate' => 'AA',
            'status' => '1',
            'sort_order' => '13',
            'events' => ['uvdesk.agent.created']
        ],
        [
            'name' => 'Customer Forgot password ',
            'description' => 'Customer Forgot password ',
            'conditions' => 'N;',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:29:"uvdesk.customer.mail_customer";s:5:"value";s:3:"CFP";}}',
            'emailTemplate' => 'CFP',
            'status' => '1',
            'sort_order' => '11',
            'events' => ['uvdesk.customer.forgot_password']
        ],
        [
            'name' => 'Collaborator Added In A Ticket',
            'description' => 'Collaborator Added In A Ticket',
            'conditions' => 'N;',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:23:"uvdesk.agent.mail_agent";s:5:"value";a:2:{s:3:"for";a:1:{i:0;s:13:"assignedAgent";}s:5:"value";s:4:"CATT";}}}',
            'emailTemplate' => 'CATT',
            'status' => '1',
            'sort_order' => '1',
            'events' => ['uvdesk.ticket.collaborator_updated']
        ],
        [
            'name' => 'Collaborator Added A Reply',
            'description' => 'Reply added by collaborator',
            'conditions' => 'N;',
            'actions' => 'a:2:{i:0;a:2:{s:4:"type";s:23:"uvdesk.agent.mail_agent";s:5:"value";s:3:"CAR";}i:1;a:2:{s:4:"type";s:29:"uvdesk.customer.mail_customer";s:5:"value";s:3:"CAR";}}',
            'emailTemplate' => 'CAR',
            'status' => '1',
            'sort_order' => '2',
            'events' => ['uvdesk.ticket.collaborator_reply']
        ],
        [
            'name' => 'Agent Forgot Password',
            'description' => 'Agent Forgot Password. ',
            'conditions' => 'N;',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:23:"uvdesk.agent.mail_agent";s:5:"value";a:2:{s:3:"for";a:1:{i:0;s:9:"baseAgent";}s:5:"value";s:3:"AFP";}}}',
            'emailTemplate' => 'AFP',
            'status' => '1',
            'sort_order' => '12',
            'events' => ['uvdesk.agent.forgot_password']
        ],
        [
            'name' => 'Assign ticket to Admin when ticket generated (for starting, please update this) ',
            'description' => 'Ticket generated by customer ',
            'conditions' => 'N;',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:26:"uvdesk.ticket.assign_agent";s:5:"value";s:1:"%";}}',
            'emailTemplate' => false,
            'assign_agent' => true,
            'status' => '1',
            'sort_order' => NULL,
            'events' => ['uvdesk.ticket.created']
        ],
        [
            'name' => 'Ticket Assign Mail',
            'description' => 'Ticket Assign Mail',
            'conditions' => 'N;',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:23:"uvdesk.agent.mail_agent";s:5:"value";a:2:{s:3:"for";a:1:{i:0;s:13:"assignedAgent";}s:5:"value";s:2:"TA";}}}',
            'emailTemplate' => 'TA',
            'status' => '1',
            'sort_order' => NULL,
            'events' => ['uvdesk.ticket.agent_updated']
        ],
        [
            'name' => 'Ticket generated by customer',
            'description' => 'Ticket generated by customer',
            'conditions' => 'N;',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:29:"uvdesk.customer.mail_customer";s:5:"value";s:4:"TGBC";}}',
            'emailTemplate' => 'TGBC',
            'status' => '1',
            'sort_order' => NULL,
            'events' => ['uvdesk.ticket.created']
        ],
        [
            'name' => 'Mail when collaborator added',
            'description' => 'Mail when collaborator added',
            'conditions' => 'N;',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:22:"mail_last_collaborator";s:5:"value";s:3:"MTC";}}',
            'emailTemplate' => 'MTC',
            'status' => '1',
            'sort_order' => NULL,
            'events' => ['uvdesk.ticket.collaborator_updated']
        ],
        [
            'name' => 'Transfer tickets from deleted agent',
            'description' => 'Transfer tickets from deleted agent',
            'conditions' => 'N;',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:15:"ticket_transfer";s:5:"value";s:18:"responsePerforming";}}',
            'emailTemplate' => false,
            'status' => '1',
            'sort_order' => NULL,
            'events' => ['uvdesk.agent.removed']
        ],
        [
            'name' => 'Ticket reply by agent - update ticket status',
            'description' => 'Ticket reply by agent - update ticket status',
            'conditions' => 'a:2:{i:0;a:3:{s:4:"type";s:6:"status";s:5:"match";s:5:"isNot";s:5:"value";s:1:"6";}i:2;a:4:{s:4:"type";s:6:"status";s:5:"match";s:5:"isNot";s:9:"operation";s:2:"&&";s:5:"value";s:1:"5";}}',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:27:"uvdesk.ticket.update_status";s:5:"value";s:1:"6";}}',
            'emailTemplate' => false,
            'status' => '1',
            'sort_order' => NULL,
            'events' => ['uvdesk.ticket.agent_reply']
        ],
        [
            'name' => 'Ticket reply by customer - update ticket status',
            'description' => 'Ticket reply by customer - update ticket status',
            'conditions' => 'a:2:{i:0;a:3:{s:4:"type";s:6:"status";s:5:"match";s:5:"isNot";s:5:"value";s:1:"1";}i:1;a:4:{s:4:"type";s:6:"status";s:5:"match";s:5:"isNot";s:9:"operation";s:2:"&&";s:5:"value";s:1:"5";}}',
            'actions' => 'a:1:{i:0;a:2:{s:4:"type";s:27:"uvdesk.ticket.update_status";s:5:"value";s:1:"1";}}',
            'emailTemplate' => false,
            'status' => '1',
            'sort_order' => NULL,
            'events' => ['uvdesk.ticket.customer_reply', 'uvdesk.ticket.collaborator_reply']
        ]
    ];

    public function load(ObjectManager $entityManager)
    {
        $availableWorkflows = $entityManager->getRepository('UVDeskAutomationBundle:Workflow')->findAll();

        if (empty($availableWorkflows)) {
            foreach (self::$seeds as $baseEvent) {

                $workflow = new AutomationEntities\Workflow();
                $workflow->setConditions([]);
                $workflow->setDateAdded(new \DateTime);
                $workflow->setDateUpdated(new \DateTime);
                $workflow_actions = unserialize($baseEvent['actions']);

                // $companyTemplate = $this->container->get('email.service')->getEmailTemplate($companyBaseEvent['emailTemplate'], $company->getId());
    
                // $emailTemplateId = null;
                // if ($companyBaseEvent['emailTemplate'] && !empty($companyTemplate)){
                //     $emailTemplateId = $companyTemplate->getId();
                // }


                foreach ($workflow_actions as $key => $action) {
                    if (1 == 1){
                        $workflow_actions[$key]['value'] = 3;
                    } 
                }

                // foreach ($workflow_actions as $key => $action) {
                //     if (isset($action['type']) && $action['type'] == 'uvdesk.ticket.assign_agent'){
                //         $workflow_actions[$key]['value'] = $user->getId();
                //     } 
                //     elseif (!empty($emailTemplateId)) {
                //         if (is_array($action['value'])) {
                //             $workflow_actions[$key]['value']['value'] = $emailTemplateId;
                //         } else {
                //             $workflow_actions[$key]['value'] = $emailTemplateId;
                //         }
                //     }
                // }
    
                $workflow->setIsPredefind(true);
                $workflow->setActions($workflow_actions);
                $workflow->setName($baseEvent['name']);
                $workflow->setStatus($baseEvent['status']);
                $workflow->setSortOrder($baseEvent['sort_order']);
                $workflow->setDescription($baseEvent['description']);
                
                $entityManager->persist($workflow);
                $entityManager->flush();
    
                foreach ($baseEvent['events'] as $eventValue) {
                    $eventObj = new AutomationEntities\WorkflowEvents();
                    $eventObj->setEventId($workflow->getId());
                    $eventObj->setEvent($eventValue);
                    $eventObj->setWorkflow($workflow);
                    $entityManager->persist($eventObj);
                }
                $entityManager->flush();
            }
        }
    }
}